// User actions
export const USER_SIGNUP = 'USER_SIGNUP';

// POSTS
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

// USER
export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const USER_LOGIN_FULFILLED = "USER_LOGIN_FULFILLED";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';

// DEVICE
export const EDIT_DEVICE_INFO = "EDIT_DEVICE_INFO";
